const items = [
  { name: "Treadmill", cost: 10, unlocked: false, mpc: 2 },
  { name: "Benchpress", cost: 100, unlocked: false, mpc: 3 },
  { name: "Protein shake", cost: 1000, unlocked: false, mpc: 5 },
  { name: "Personal trainer", cost: 10000, unlocked: false, mpc: 20 },
  { name: "Gym", cost: 100000, unlocked: false, mpc: 50 },
  { name: "Chalk", cost: 50, unlocked: false, mpc: 0.5 },
  { name: "Belt", cost: 500, unlocked: false, mpc: 2 },
  { name: "Straps", cost: 750, unlocked: false, mpc: 2.5 },
  { name: "Wrist wraps", cost: 600, unlocked: false, mpc: 2 },
  { name: "Knee wraps", cost: 800, unlocked: false, mpc: 2.5 },
  { name: "Pre-workout", cost: 1500, unlocked: false, mpc: 7 },
  { name: "Protein powder", cost: 2000, unlocked: false, mpc: 8 },
  { name: "Creatine", cost: 2500, unlocked: false, mpc: 10 },
  { name: "Cardio", cost: 3000, unlocked: false, mpc: 5 },
  { name: "Deadlift", cost: 5000, unlocked: false, mpc: 15 },
  { name: "Bench", cost: 6000, unlocked: false, mpc: 12 },
  { name: "Squat", cost: 7000, unlocked: false, mpc: 18 },
  { name: "Steroids", cost: 20000, unlocked: false, mpc: 50 },
  { name: "Bicep curl", cost: 3000, unlocked: false, mpc: 6 },
  { name: "Sauna", cost: 8000, unlocked: false, mpc: 5 },
  { name: "Energy drinks", cost: 1200, unlocked: false, mpc: 3 },
  { name: "Gymbro", cost: 15000, unlocked: false, mpc: 25 },
  { name: "OldCA clothes", cost: 5000, unlocked: false, mpc: 10 },
  { name: "Dumbbells", cost: 4000, unlocked: false, mpc: 8 },
  { name: "Kettlebell", cost: 3500, unlocked: false, mpc: 7 },
  { name: "Barbell", cost: 4500, unlocked: false, mpc: 9 },
  { name: "Resistance bands", cost: 2000, unlocked: false, mpc: 4 },
  { name: "Massage gun", cost: 10000, unlocked: false, mpc: 5 },
  { name: "Lifting shoes", cost: 7000, unlocked: false, mpc: 6 },
  { name: "Posing mirror", cost: 5000, unlocked: false, mpc: 4 },
  { name: "Home gym setup", cost: 50000, unlocked: false, mpc: 30 },
  { name: "Girlfriend", cost: 1000000, unlocked: false, mpc: 100 },
];

export default items;
